### ISSUE TITLE
Semantic versioning releases

### ISSUE THREAD

**Issue by charleso** [hedgehogqa/scala-hedgehog#103]
I only want to do this if it's automated though. The easiest way would be to do another build/publish when a Git tag is added. That said, it would be _great_ if we could add a PR process for adding a versioning so we can run [mima](https://github.com/lightbend/mima).

**Comment by charleso** [comment]
I've added a tag-based release build for now, and released 0.1.0. I would still very much like a way to PR the releases and test against mima at some point

**Comment by tmcgilchrist** [comment]
What's the latest on setting up the SBT binary dependency?
Should I be using a git sha as described in the README or pointing to a version?

**Comment by charleso** [comment]
At this point it doesn't matter. Every commit is still going to be
published. I'll try to create semantic versions for every change too. The
only thing that I haven't got yet that I would like is a PR-driven release
to check binary compatibility.

I would probably use the semantic version as it's just easier to remember
and track.

Kevin is also working on a Maven central sync which will be nice.
