### ISSUE TITLE
Usage question: Gen[Double] => Double

### ISSUE THREAD

**Issue by pk044** [hedgehogqa/scala-hedgehog#130]
I'm currently trying to figure out if it's possible to pull a value from `Gen`? I looked at the tutorials, but it seems like it's not possible to get something else than `Gen`/`Property` - I think the value can only be accessed within a test?

I am benchmarking property-based test libraries, and one of the cases I want to cover is to see how fast scala-hedgehog can generate e.g. a Double.

Thanks for the effort put into this project by the way! :)

**Comment by charleso** [comment]
Hi Pawel,

Gen is just a wrapper around a function, which you can call directly, you
just need size/seed. Something _like_ this, but I don't have my computer
with me.

aGen.run(Size(100) -> Seed.fromTime()).value._2.head

The size can be anything from 1 to 100, but shouldn't affect performance.

I'm using the exact same RNG as scalaprops, but there's almost certainly
more boxing and extra stuff in Hedghehog.

I'm curious how the testing goes. I haven't put much effort in to
performance except to make sure shrinking doesn't have a memory or
strictness leak (you will need to perform a full Property test for that,
not just the code above).

Good luck and let me know how it goes :)

Charles

**Comment by pk044** [comment]
Thank you very much for the fast response! I'll post the comparison here once I make sure the benchmark gives fair results :)
