### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by mpilquist** [hedgehogqa/scala-hedgehog#145]
Any objections to publishing to Maven Central and following semver? Git hash versioning and bintray make it more difficult to publish integration projects -- e.g., an munit + hedgehog bridge project.

**Comment by charleso** [comment]
No objections at all! I'm sorry it's not already. I got about 90% of the way to automating it (I think). There's a branch with a script that uses the bintray sync.

https://github.com/hedgehogqa/scala-hedgehog/compare/topic/maven-central-sync?expand=1

The only problem at the moment is my attempt to publish to a separate bintray repository for maven.

https://github.com/hedgehogqa/scala-hedgehog/blob/master/.travis.yml#L25

I'm afraid I haven't got any time for fixing this, and any help would be much appreciated.

**Comment by Kevin-Lee** [comment]
@charleso I need this to use Hedgehog in my company projects. 🙂I think I can help you with this issue. In fact, there's already PR (#129) doing it as you know.
So Charles, do you mind using GitHub Actions for build and release instead of Travis?

By the way, my PR needs some update which I can do today if you want.

**Comment by charleso** [comment]
Hey @Kevin-Lee . I don't mind using Github actions, but that's not actually required? I've got a branch that's ready to go:

https://github.com/hedgehogqa/scala-hedgehog/compare/topic/maven-central-sync

There is currently an error publishing in tagged builds but I can't remember what it is, something to do with setting maven to true not being applied

https://github.com/hedgehogqa/scala-hedgehog/blob/master/.travis.yml#L23

Sorry I can't help you more than that at the moment.

**Comment by Kevin-Lee** [comment]
No, GitHub Actions is not required. I was just asking as I already created PR with it. 🙂 I found it simple and nice to use so moved all my CI/CD to GitHub Actions now, but it's all good without it too.

OK, I think I can help you with that build failure issue. Do you mind if I work on it?

By the way, I'm not sure if you remember this, but I once mentioned that to use Bintray's Maven Central sync feature, you need to link your Bintray repos to JCenter first, but I guess you've already done this, haven't you?

**Comment by charleso** [comment]
> OK, I think I can help you with that build failure issue. Do you mind if I work on it?

Please go for it!

 > By the way, I'm not sure if you remember this, but I once mentioned that to use Bintray's Maven Central sync feature, you need to link your Bintray repos to JCenter first, but I guess you've already done this, haven't you?

Yep done that part! :)

**Comment by Kevin-Lee** [comment]
@charleso @mpilquist I've never done any project for Scala.js before. So in `sbt publish`, should I do anything extra for Scala.js?

**Comment by Kevin-Lee** [comment]
I'm sorry Never mind. It looks all good.

**Comment by Kevin-Lee** [comment]
For those who are interested in this issue, the latest release to Maven Central, but I know what it is and will fix it as soon as I can.

**Comment by Kevin-Lee** [comment]
@mpilquist Could you please confirm that this ticket can be closed? Hedgehog is now available on Maven Central with SemVer.

| Project | Maven Central | Maven Central (JS) | Bintray   |  
|:-------:|:-------------:|:-------------:|:---------:|
| hedgehog-core | [![Maven Central](https://maven-badges.herokuapp.com/maven-central/qa.hedgehog/hedgehog-core_2.13/badge.svg)](https://search.maven.org/artifact/qa.hedgehog/hedgehog-core_2.13) | [![Maven Central](https://maven-badges.herokuapp.com/maven-central/qa.hedgehog/hedgehog-core_sjs1_2.13/badge.svg)](https://search.maven.org/artifact/qa.hedgehog/hedgehog-core_sjs1_2.13) | [ ![Download](https://api.bintray.com/packages/hedgehogqa/scala-hedgehog-maven/hedgehog-core/images/download.svg) ](https://bintray.com/hedgehogqa/scala-hedgehog-maven/hedgehog-core/_latestVersion) |
| hedgehog-runner | [![Maven Central](https://maven-badges.herokuapp.com/maven-central/qa.hedgehog/hedgehog-runner_2.13/badge.svg)](https://search.maven.org/artifact/qa.hedgehog/hedgehog-runner_2.13) | [![Maven Central](https://maven-badges.herokuapp.com/maven-central/qa.hedgehog/hedgehog-runner_sjs1_2.13/badge.svg)](https://search.maven.org/artifact/qa.hedgehog/hedgehog-runner_sjs1_2.13) | [ ![Download](https://api.bintray.com/packages/hedgehogqa/scala-hedgehog-maven/hedgehog-runner/images/download.svg) ](https://bintray.com/hedgehogqa/scala-hedgehog-maven/hedgehog-runner/_latestVersion) |
| hedgehog-sbt | [![Maven Central](https://maven-badges.herokuapp.com/maven-central/qa.hedgehog/hedgehog-sbt_2.13/badge.svg)](https://search.maven.org/artifact/qa.hedgehog/hedgehog-sbt_2.13) | [![Maven Central](https://maven-badges.herokuapp.com/maven-central/qa.hedgehog/hedgehog-sbt_sjs1_2.13/badge.svg)](https://search.maven.org/artifact/qa.hedgehog/hedgehog-sbt_sjs1_2.13) | [ ![Download](https://api.bintray.com/packages/hedgehogqa/scala-hedgehog-maven/hedgehog-sbt/images/download.svg) ](https://bintray.com/hedgehogqa/scala-hedgehog-maven/hedgehog-sbt/_latestVersion) |
| hedgehog-minitest | [![Maven Central](https://maven-badges.herokuapp.com/maven-central/qa.hedgehog/hedgehog-minitest_2.13/badge.svg)](https://search.maven.org/artifact/qa.hedgehog/hedgehog-minitest_2.13) | [![Maven Central](https://maven-badges.herokuapp.com/maven-central/qa.hedgehog/hedgehog-minitest_sjs1_2.13/badge.svg)](https://search.maven.org/artifact/qa.hedgehog/hedgehog-minitest_sjs1_2.13) | [ ![Download](https://api.bintray.com/packages/hedgehogqa/scala-hedgehog-maven/hedgehog-minitest/images/download.svg) ](https://bintray.com/hedgehogqa/scala-hedgehog-maven/hedgehog-minitest/_latestVersion) |

* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-core_sjs1_2.11/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-core_sjs1_2.12/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-core_sjs1_2.13/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-core_2.11/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-core_2.12/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-core_2.13/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-runner_sjs1_2.11/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-runner_sjs1_2.12/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-runner_sjs1_2.13/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-runner_2.11/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-runner_2.12/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-runner_2.13/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-sbt_sjs1_2.11/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-sbt_sjs1_2.12/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-sbt_sjs1_2.13/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-sbt_2.11/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-sbt_2.12/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-sbt_2.13/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-minitest_sjs1_2.11/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-minitest_sjs1_2.12/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-minitest_sjs1_2.13/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-minitest_2.11/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-minitest_2.12/0.4.2/
* https://repo1.maven.org/maven2/qa/hedgehog/hedgehog-minitest_2.13/0.4.2/

**Comment by mpilquist** [comment]
Awesome!
