### ISSUE TITLE
Integration with minitest

### ISSUE THREAD

**Issue by dwestheide** [hedgehogqa/scala-hedgehog#160]
I'd like to see an integration between [minitest](https://github.com/monix/minitest) and Hedgehog. They already have an integration module for ScalaCheck. I am not sure whether a Hedgehog integration should best be a module of minitest or of scala-hedgehog. Given that scala-hedgehog doesn't have proper releases yet, I think that having it in the scala-hedgehog project would work better.

I already implemented the integration. Given minitest's nature, the integration is minimal and requires only a single file with 30-40 lines of code. If there is interest in having this integration in a scala-hedgehog sbt sub project, I will open a PR.

**Comment by charleso** [comment]
@dwestheide see my comment on #158

**Comment by charleso** [comment]
(Thanks for reaching out!)
