### ISSUE TITLE
Port of QuickCheck's labelledExamples?

### ISSUE THREAD

**Issue by dwijnand** [hedgehogqa/scala-hedgehog#163]
It doesn't look like haskell-hedgehog even has this!  I would love to debug my generators and labelling with it.

I'm actually so keen that I might give a shot at implementing it, but I wouldn't how to do it and I can't even steal from haskell-hedgehog here...  Any advice/tips/mentoring?

**Comment by charleso** [comment]
@dwestheide I'd love to help with this, but I'm so limited in time these days. :( I would probably look at the quickcheck implementation, read the hedgehog data model, and see if you can see how the two line up. I'm happy to do a zoom/meet or chat session with you at some point if that helps?

**Comment by dwijnand** [comment]
Thanks, Charles.  I'll have another go at reading the hedgehog data model, see if I can make a jab at implementing this, so we can look at some code together.
