### ISSUE TITLE
Support Dotty (Scala 3.0.0-M1)

### ISSUE THREAD

**Issue by Kevin-Lee** [hedgehogqa/scala-hedgehog#180]
Since Scala 3.0.0-M1 (Dotty) has been released, I think it's time to support Dotty.
I'm currently working on it but having an issue with macro used in Minitest.
Fortunately, there is an open [PR](https://github.com/monix/minitest/pull/66) to support Dotty on the Minitest repo so I'll finish it once that PR is merged and released.

**Comment by larsrh** [comment]
Release should be out this weekend.

**Comment by Kevin-Lee** [comment]
@larsrh That's great! Thanks Lars.

**Comment by larsrh** [comment]
@avasil has published 2.9.0 of minitest

**Comment by Kevin-Lee** [comment]
@larsrh Awesome! Thank you so much!
