### ISSUE TITLE
ScalaTest runs Hedgehog even when it doesn't have required tag

### ISSUE THREAD

**Issue by meirmaor** [hedgehogqa/scala-hedgehog#200]
We run tests with ScalaTest Runner (often from SBT), and we supply -n someTag  in order to control which tests are run when. 
It appears our single HedgeHog test runs regardless of what we specify in -n . Despite the property test not having any tag, nor is does the class have any tag via annotation. 

This might be a Scala Test Runner issue, but I'm trying here, especially since I'm interested in a workaround. 
Can we run the propery checks as a method from a different type test. an equivalent to the check method in ScalaCheck, so my class will extend AnyFlatSpec, or AnyFunSuite or such from scalatest and inside a specifc test we will call hedgehog to do it's magic.

**Comment by charleso** [comment]
Hi @meirmaor, I'm afraid Hedgehog doesn't have a ScalaTest integration, at least not in this repository. I don't quite know what you mean. Did you have an example or link to the test that might give us some context?

**Comment by meirmaor** [comment]
So this is my workaround, not sure this is the best way to call hedgehog from within scalatest but it seems to work. 

class myClass extends AnyFlatSpec {
   val myProp : Prop = property(...)
   private val seed: Seed = Seed.fromLong(0l)
   
	"something" should "work correctly" in {
		val report = Property.check(myProp.withConfig(PropertyConfig.default),myProp.result,seed)
		if (report.status != Status.ok) {
			val reason = Test.renderReport(
				this.getClass.getName,
				commutative,
				report,
				ansiCodesSupported = true
			)
			throw new AssertionError(reason)
		}
	}  
}

**Comment by charleso** [comment]
> So this is my workaround, not sure this is the best way to call hedgehog from within scalatest but it seems to work.

Yeah that looks about right (except maybe hard coding the seed). You would ideally have a function you can call just after `in` that you mixin that handles all of the boilerplate.

There is an issue to track this request. As a word of warning this repository if not very actively maintained, so I wouldn't expect it to be implemented any time soon.

https://github.com/hedgehogqa/scala-hedgehog/issues/158

Regarding your original question:

> and we supply -n someTag

I'm afraid that's a pure ScalaTest question, I don't really know what the issue might be. Does it work for other tests?

Did you mind if we close this issue?
