### ISSUE TITLE
State testing

### ISSUE THREAD

**Issue by charleso** [hedgehogqa/scala-hedgehog#26]
https://github.com/hedgehogqa/haskell-hedgehog/blob/7516d04673563455a55cf69eb1c490fbbb7f2a5f/hedgehog/src/Hedgehog/Internal/State.hs#L1

- I'm not sure if the use of our [state-based random](https://github.com/hedgehogqa/scala-hedgehog/blob/master/core/src/main/scala/hedgehog/random/MersenneTwister64.scala#L1) implementation will need to be switched to [splitmix](https://github.com/hedgehogqa/haskell-hedgehog/blob/2bd6062eaf9f83a88f47e5545fda9a183024bb2a/hedgehog/src/Hedgehog/Internal/Seed.hs). This might be a good excuse to do it.
- I would _really_ like it if we kept state separate in its own [state package](https://github.com/hedgehogqa/scala-hedgehog/tree/master/state), which is something the haskell implementation doesn't do.

**Comment by charleso** [comment]
My current WIP branch: https://github.com/hedgehogqa/scala-hedgehog/compare/topic/state

**Comment by charleso** [comment]
I've finally got something working on my branch. It's just sequential at the moment. I want to tidy it up which might take another day or two, and get it merged to master.

**Comment by charleso** [comment]
We now have state-based testing \o/

**Comment by moodmosaic** [comment]
:tada:
