### ISSUE TITLE
Publish scaladoc

### ISSUE THREAD

**Issue by raronson** [hedgehogqa/scala-hedgehog#41]
Would be nice to browse the API through scaladoc

**Comment by charleso** [comment]
Looks like we get jar _and doc hosting on jitpack.io:

https://jitpack.io/

**Comment by Kevin-Lee** [comment]
https://hedgehogqa.github.io/scala-hedgehog
It's too late but is now available.
<img width="495" alt="Screen Shot 2021-11-22 at 2 06 41 am" src="https://user-images.githubusercontent.com/2307335/142767533-20e1cd5c-bd9e-405b-b427-d1f9e9721ffe.png">
