### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by charleso** [hedgehogqa/scala-hedgehog#8]
- Might be good to work belongs here vs in a more general place. 
- A visible example would be nice.
- Some guidelines around scala coding
- How this is a copy of the haskell one, and where/why the difference are

**Comment by mmynsted** [comment]
How about a tutorial like is available for the fsharp version? 
[fsharp tutorial](https://github.com/hedgehogqa/fsharp-hedgehog/blob/master/doc/tutorial.md)

**Comment by charleso** [comment]
We could use [sbt microsites](https://47deg.github.io/sbt-microsites/) to generate the doc.

There is also the option of hosting the doc under https://hedgehog.qa/scala (or something like that).

**Comment by charleso** [comment]
For now I have added a basic markdown tutorial, which hopefully some people find useful.

https://github.com/hedgehogqa/scala-hedgehog/blob/master/doc/tutorial.md
